# Generated by Django 2.1.7 on 2019-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US-Dollar'), ('YPY', 'Japanese-Yen')], default='USD', max_length=3)),
                ('rate_to_dollars', models.FloatField()),
            ],
        ),
    ]
