# Generated by Django 2.1.7 on 2019-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_conv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate_to_dollars',
            field=models.FloatField(default=1),
        ),
    ]
